insert into t_grade (id, course_id, student_id, status, grade, sem_taken, year) values (1, 'CMSC 674', 37, ' taking ', ' INC', ' 2nd Sem', '2020');
insert into t_grade (id, course_id, student_id, status, grade, sem_taken, year) values (2, 'CMSC 190', 92, ' taking ', ' INC', '1st Sem ', '2039');
insert into t_grade (id, course_id, student_id, status, grade, sem_taken, year) values (3, 'CMSC 795', 84, ' taking ', ' 5 ', '1st Sem ', '2070');
insert into t_grade (id, course_id, student_id, status, grade, sem_taken, year) values (4, 'CMSC 505', 44, 'taken  ', ' 2.25 ', ' 2nd Sem', '2074');
insert into t_grade (id, course_id, student_id, status, grade, sem_taken, year) values (5, 'CMSC 072', 52, ' taking ', ' 5 ', ' 2nd Sem', '2096');
insert into t_grade (id, course_id, student_id, status, grade, sem_taken, year) values (6, 'CMSC 614', 20, 'taken  ', ' 2.5 ', ' 2nd Sem', '2009');
insert into t_grade (id, course_id, student_id, status, grade, sem_taken, year) values (7, 'CMSC 474', 89, ' taking ', ' 2.75 ', ' 2nd Sem', '2067');
insert into t_grade (id, course_id, student_id, status, grade, sem_taken, year) values (8, 'CMSC 095', 96, ' taking ', ' 4 ', ' 2nd Sem', '2018');
insert into t_grade (id, course_id, student_id, status, grade, sem_taken, year) values (9, 'CMSC 895', 3, ' taking ', ' INC', ' 2nd Sem', '2023');
insert into t_grade (id, course_id, student_id, status, grade, sem_taken, year) values (10, 'CMSC 613', 16, 'taken  ', ' INC', ' 2nd Sem', '2060');
insert into t_grade (id, course_id, student_id, status, grade, sem_taken, year) values (11, 'CMSC 694', 26, ' taking ', ' 4 ', '1st Sem ', '2078');
insert into t_grade (id, course_id, student_id, status, grade, sem_taken, year) values (12, 'CMSC 847', 57, ' taking ', ' 2.25 ', '1st Sem ', '2009');
insert into t_grade (id, course_id, student_id, status, grade, sem_taken, year) values (13, 'CMSC 190', 9, 'taken  ', ' INC', ' 2nd Sem', '2060');
insert into t_grade (id, course_id, student_id, status, grade, sem_taken, year) values (14, 'CMSC 901', 61, 'taken  ', ' INC', '1st Sem ', '2022');
insert into t_grade (id, course_id, student_id, status, grade, sem_taken, year) values (15, 'CMSC 937', 66, ' taking ', ' INC', '1st Sem ', '2089');
insert into t_grade (id, course_id, student_id, status, grade, sem_taken, year) values (16, 'CMSC 682', 63, ' taking ', ' INC', ' 2nd Sem', '2027');
insert into t_grade (id, course_id, student_id, status, grade, sem_taken, year) values (17, 'CMSC 321', 45, 'taken  ', ' INC', ' 2nd Sem', '2068');
insert into t_grade (id, course_id, student_id, status, grade, sem_taken, year) values (18, 'CMSC 750', 51, ' taking ', ' INC', '1st Sem ', '2082');
insert into t_grade (id, course_id, student_id, status, grade, sem_taken, year) values (19, 'CMSC 117', 59, ' taking ', ' INC', '1st Sem ', '2040');
insert into t_grade (id, course_id, student_id, status, grade, sem_taken, year) values (20, 'CMSC 280', 92, ' taking ', ' INC', '1st Sem ', '2058');
insert into t_grade (id, course_id, student_id, status, grade, sem_taken, year) values (21, 'CMSC 817', 76, ' taking ', ' INC', ' 2nd Sem', '2046');
insert into t_grade (id, course_id, student_id, status, grade, sem_taken, year) values (22, 'CMSC 981', 85, 'taken  ', ' INC', '1st Sem ', '2005');
insert into t_grade (id, course_id, student_id, status, grade, sem_taken, year) values (23, 'CMSC 584', 61, ' taking ', ' 4 ', ' 2nd Sem', '2045');
insert into t_grade (id, course_id, student_id, status, grade, sem_taken, year) values (24, 'CMSC 286', 88, 'taken  ', ' INC', '1st Sem ', '2017');
insert into t_grade (id, course_id, student_id, status, grade, sem_taken, year) values (25, 'CMSC 664', 21, 'taken  ', ' INC', '1st Sem ', '2003');
insert into t_grade (id, course_id, student_id, status, grade, sem_taken, year) values (26, 'CMSC 285', 13, 'taken  ', ' 4 ', ' 2nd Sem', '2081');
insert into t_grade (id, course_id, student_id, status, grade, sem_taken, year) values (27, 'CMSC 957', 6, ' taking ', ' INC', '1st Sem ', '2058');
insert into t_grade (id, course_id, student_id, status, grade, sem_taken, year) values (28, 'CMSC 412', 60, ' taking ', ' 5 ', ' 2nd Sem', '2022');
insert into t_grade (id, course_id, student_id, status, grade, sem_taken, year) values (29, 'CMSC 377', 1, ' taking ', ' 5 ', '1st Sem ', '2077');
insert into t_grade (id, course_id, student_id, status, grade, sem_taken, year) values (30, 'CMSC 544', 35, ' taking ', ' INC', '1st Sem ', '2092');
insert into t_grade (id, course_id, student_id, status, grade, sem_taken, year) values (31, 'CMSC 645', 1, 'taken  ', ' INC', '1st Sem ', '2024');
insert into t_grade (id, course_id, student_id, status, grade, sem_taken, year) values (32, 'CMSC 632', 27, 'taken  ', ' 5 ', '1st Sem ', '2058');
insert into t_grade (id, course_id, student_id, status, grade, sem_taken, year) values (33, 'CMSC 150', 5, ' taking ', ' 5 ', ' 2nd Sem', '2020');
insert into t_grade (id, course_id, student_id, status, grade, sem_taken, year) values (34, 'CMSC 457', 53, 'taken  ', ' INC', ' 2nd Sem', '2095');
insert into t_grade (id, course_id, student_id, status, grade, sem_taken, year) values (35, 'CMSC 170', 24, ' taking ', ' 5 ', '1st Sem ', '2091');
insert into t_grade (id, course_id, student_id, status, grade, sem_taken, year) values (36, 'CMSC 951', 87, ' taking ', ' 5 ', '1st Sem ', '2084');
insert into t_grade (id, course_id, student_id, status, grade, sem_taken, year) values (37, 'CMSC 608', 62, ' taking ', ' 2.25 ', ' 2nd Sem', '2084');
insert into t_grade (id, course_id, student_id, status, grade, sem_taken, year) values (38, 'CMSC 806', 88, ' taking ', ' INC', ' 2nd Sem', '2046');
insert into t_grade (id, course_id, student_id, status, grade, sem_taken, year) values (39, 'CMSC 280', 47, 'taken  ', ' INC', ' 2nd Sem', '2091');
insert into t_grade (id, course_id, student_id, status, grade, sem_taken, year) values (40, 'CMSC 741', 78, ' taking ', ' 5 ', '1st Sem ', '2049');
insert into t_grade (id, course_id, student_id, status, grade, sem_taken, year) values (41, 'CMSC 066', 21, ' taking ', ' INC', '1st Sem ', '2014');
insert into t_grade (id, course_id, student_id, status, grade, sem_taken, year) values (42, 'CMSC 710', 74, ' taking ', ' INC', '1st Sem ', '2002');
insert into t_grade (id, course_id, student_id, status, grade, sem_taken, year) values (43, 'CMSC 762', 8, 'taken  ', ' 5 ', ' 2nd Sem', '2078');
insert into t_grade (id, course_id, student_id, status, grade, sem_taken, year) values (44, 'CMSC 279', 61, ' taking ', ' 4 ', ' 2nd Sem', '2020');
insert into t_grade (id, course_id, student_id, status, grade, sem_taken, year) values (45, 'CMSC 909', 92, ' taking ', ' 4 ', ' 2nd Sem', '2019');
insert into t_grade (id, course_id, student_id, status, grade, sem_taken, year) values (46, 'CMSC 720', 64, ' taking ', ' INC', '1st Sem ', '2049');
insert into t_grade (id, course_id, student_id, status, grade, sem_taken, year) values (47, 'CMSC 956', 65, 'taken  ', ' INC', '1st Sem ', '2033');
insert into t_grade (id, course_id, student_id, status, grade, sem_taken, year) values (48, 'CMSC 041', 48, ' taking ', ' 5 ', ' 2nd Sem', '2046');
insert into t_grade (id, course_id, student_id, status, grade, sem_taken, year) values (49, 'CMSC 603', 5, 'taken  ', ' 4 ', ' 2nd Sem', '2025');
insert into t_grade (id, course_id, student_id, status, grade, sem_taken, year) values (50, 'CMSC 753', 13, ' taking ', ' 4 ', '1st Sem ', '2020');
insert into t_grade (id, course_id, student_id, status, grade, sem_taken, year) values (51, 'CMSC 763', 82, 'taken  ', ' INC', ' 2nd Sem', '2025');
insert into t_grade (id, course_id, student_id, status, grade, sem_taken, year) values (52, 'CMSC 026', 60, 'taken  ', ' INC', ' 2nd Sem', '2018');
insert into t_grade (id, course_id, student_id, status, grade, sem_taken, year) values (53, 'CMSC 441', 87, 'taken  ', ' 5 ', '1st Sem ', '2032');
insert into t_grade (id, course_id, student_id, status, grade, sem_taken, year) values (54, 'CMSC 650', 27, ' taking ', ' 4 ', ' 2nd Sem', '2097');
insert into t_grade (id, course_id, student_id, status, grade, sem_taken, year) values (55, 'CMSC 078', 58, 'taken  ', ' INC', '1st Sem ', '2062');
insert into t_grade (id, course_id, student_id, status, grade, sem_taken, year) values (56, 'CMSC 205', 8, 'taken  ', ' 3 ', '1st Sem ', '2052');
insert into t_grade (id, course_id, student_id, status, grade, sem_taken, year) values (57, 'CMSC 913', 72, 'taken  ', ' INC', '1st Sem ', '2037');
insert into t_grade (id, course_id, student_id, status, grade, sem_taken, year) values (58, 'CMSC 393', 24, 'taken  ', ' 5 ', ' 2nd Sem', '2065');
insert into t_grade (id, course_id, student_id, status, grade, sem_taken, year) values (59, 'CMSC 806', 48, 'taken  ', ' INC', ' 2nd Sem', '2047');
insert into t_grade (id, course_id, student_id, status, grade, sem_taken, year) values (60, 'CMSC 941', 57, 'taken  ', ' 5 ', '1st Sem ', '2024');
insert into t_grade (id, course_id, student_id, status, grade, sem_taken, year) values (61, 'CMSC 036', 58, 'taken  ', ' 5 ', '1st Sem ', '2048');
insert into t_grade (id, course_id, student_id, status, grade, sem_taken, year) values (62, 'CMSC 151', 29, 'taken  ', ' INC', '1st Sem ', '2004');
insert into t_grade (id, course_id, student_id, status, grade, sem_taken, year) values (63, 'CMSC 068', 1, 'taken  ', ' 5 ', ' 2nd Sem', '2073');
insert into t_grade (id, course_id, student_id, status, grade, sem_taken, year) values (64, 'CMSC 276', 15, ' taking ', ' 5 ', '1st Sem ', '2088');
insert into t_grade (id, course_id, student_id, status, grade, sem_taken, year) values (65, 'CMSC 039', 100, ' taking ', ' INC', '1st Sem ', '2027');
insert into t_grade (id, course_id, student_id, status, grade, sem_taken, year) values (66, 'CMSC 722', 75, 'taken  ', ' INC', ' 2nd Sem', '2032');
insert into t_grade (id, course_id, student_id, status, grade, sem_taken, year) values (67, 'CMSC 302', 85, 'taken  ', ' INC', ' 2nd Sem', '2004');
insert into t_grade (id, course_id, student_id, status, grade, sem_taken, year) values (68, 'CMSC 755', 30, ' taking ', ' 3 ', ' 2nd Sem', '2073');
insert into t_grade (id, course_id, student_id, status, grade, sem_taken, year) values (69, 'CMSC 947', 83, 'taken  ', ' 2.5 ', '1st Sem ', '2001');
insert into t_grade (id, course_id, student_id, status, grade, sem_taken, year) values (70, 'CMSC 732', 25, ' taking ', ' INC', '1st Sem ', '2083');
insert into t_grade (id, course_id, student_id, status, grade, sem_taken, year) values (71, 'CMSC 865', 16, ' taking ', ' INC', ' 2nd Sem', '2002');
insert into t_grade (id, course_id, student_id, status, grade, sem_taken, year) values (72, 'CMSC 355', 62, ' taking ', ' INC', ' 2nd Sem', '2014');
insert into t_grade (id, course_id, student_id, status, grade, sem_taken, year) values (73, 'CMSC 188', 45, ' taking ', ' INC', ' 2nd Sem', '2044');
insert into t_grade (id, course_id, student_id, status, grade, sem_taken, year) values (74, 'CMSC 371', 22, ' taking ', ' 5 ', ' 2nd Sem', '2029');
insert into t_grade (id, course_id, student_id, status, grade, sem_taken, year) values (75, 'CMSC 310', 82, 'taken  ', ' INC', '1st Sem ', '2003');
insert into t_grade (id, course_id, student_id, status, grade, sem_taken, year) values (76, 'CMSC 901', 78, 'taken  ', ' 5 ', ' 2nd Sem', '2025');
insert into t_grade (id, course_id, student_id, status, grade, sem_taken, year) values (77, 'CMSC 438', 4, 'taken  ', ' INC', '1st Sem ', '2057');
insert into t_grade (id, course_id, student_id, status, grade, sem_taken, year) values (78, 'CMSC 481', 39, ' taking ', ' 4 ', ' 2nd Sem', '2012');
insert into t_grade (id, course_id, student_id, status, grade, sem_taken, year) values (79, 'CMSC 533', 66, ' taking ', ' 3 ', '1st Sem ', '2053');
insert into t_grade (id, course_id, student_id, status, grade, sem_taken, year) values (80, 'CMSC 719', 4, 'taken  ', ' INC', ' 2nd Sem', '2077');
insert into t_grade (id, course_id, student_id, status, grade, sem_taken, year) values (81, 'CMSC 975', 46, ' taking ', ' INC', ' 2nd Sem', '2046');
insert into t_grade (id, course_id, student_id, status, grade, sem_taken, year) values (82, 'CMSC 943', 86, ' taking ', ' INC', ' 2nd Sem', '2054');
insert into t_grade (id, course_id, student_id, status, grade, sem_taken, year) values (83, 'CMSC 116', 97, ' taking ', ' 4 ', '1st Sem ', '2002');
insert into t_grade (id, course_id, student_id, status, grade, sem_taken, year) values (84, 'CMSC 062', 21, ' taking ', ' INC', ' 2nd Sem', '2054');
insert into t_grade (id, course_id, student_id, status, grade, sem_taken, year) values (85, 'CMSC 684', 85, 'taken  ', ' INC', ' 2nd Sem', '2099');
insert into t_grade (id, course_id, student_id, status, grade, sem_taken, year) values (86, 'CMSC 185', 38, 'taken  ', ' 5 ', '1st Sem ', '2056');
insert into t_grade (id, course_id, student_id, status, grade, sem_taken, year) values (87, 'CMSC 781', 55, ' taking ', ' INC', '1st Sem ', '2086');
insert into t_grade (id, course_id, student_id, status, grade, sem_taken, year) values (88, 'CMSC 427', 49, 'taken  ', ' INC', ' 2nd Sem', '2035');
insert into t_grade (id, course_id, student_id, status, grade, sem_taken, year) values (89, 'CMSC 123', 38, 'taken  ', ' 2.75 ', ' 2nd Sem', '2099');
insert into t_grade (id, course_id, student_id, status, grade, sem_taken, year) values (90, 'CMSC 237', 23, 'taken  ', ' 5 ', '1st Sem ', '2026');
insert into t_grade (id, course_id, student_id, status, grade, sem_taken, year) values (91, 'CMSC 321', 23, ' taking ', ' 4 ', ' 2nd Sem', '2055');
insert into t_grade (id, course_id, student_id, status, grade, sem_taken, year) values (92, 'CMSC 294', 90, 'taken  ', ' INC', ' 2nd Sem', '2074');
insert into t_grade (id, course_id, student_id, status, grade, sem_taken, year) values (93, 'CMSC 885', 79, ' taking ', ' INC', '1st Sem ', '2069');
insert into t_grade (id, course_id, student_id, status, grade, sem_taken, year) values (94, 'CMSC 727', 61, ' taking ', ' 5 ', ' 2nd Sem', '2009');
insert into t_grade (id, course_id, student_id, status, grade, sem_taken, year) values (95, 'CMSC 217', 64, ' taking ', ' 3 ', '1st Sem ', '2057');
insert into t_grade (id, course_id, student_id, status, grade, sem_taken, year) values (96, 'CMSC 385', 39, ' taking ', ' INC', '1st Sem ', '2083');
insert into t_grade (id, course_id, student_id, status, grade, sem_taken, year) values (97, 'CMSC 669', 7, 'taken  ', ' 5 ', ' 2nd Sem', '2095');
insert into t_grade (id, course_id, student_id, status, grade, sem_taken, year) values (98, 'CMSC 445', 12, ' taking ', ' INC', ' 2nd Sem', '2046');
insert into t_grade (id, course_id, student_id, status, grade, sem_taken, year) values (99, 'CMSC 219', 74, ' taking ', ' INC', '1st Sem ', '2065');
insert into t_grade (id, course_id, student_id, status, grade, sem_taken, year) values (100, 'CMSC 185', 63, 'taken  ', ' 3 ', ' 2nd Sem', '2082');
